# Generated by Django 6.0.3 on 2026-03-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="print",
            new_name="price",
        ),
    ]
