# Generated by Django 6.0.3 on 2026-03-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_print_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="Product Discount 20 percent"
                    ),
                ),
                ("discount", models.FloatField()),
            ],
        ),
    ]
